version: '3'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/5cloths
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network
  mongo-init:
    image: mongo
    command: 'mongosh mongodb://mongodb:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.10 < init-mongo.js'
    depends_on:
      - mongodb
    networks:
      - node-network
volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
